Fix some types
primefaces/primereact pull request #1909
Opened 2021-03-26 14:14 UTC by mateusnava

Fixed #1908

2021-03-29 11:52 UTC, master117 requested changes
Looks good to me, but PrimeReact so far uses any[] instead of Array[] in nearly all places.

2021-03-29 11:52 UTC, master117 commented on src/components/cascadeselect/CascadeSelect.d.ts
> +    options?: Array<any>;
I believe any[] would fit better with the rest of PrimeReact typing style from what I have seen. Array\<any\> is only used in Timeline.d.ts, any[] is used in 36 places across 21 files.

```suggestion
    options?: any[];
```

2021-03-29 11:52 UTC, master117 commented on src/components/cascadeselect/CascadeSelect.d.ts
> +    optionGroupChildren?: Array<any>;
I believe any[] would fit better with the rest of PrimeReact typing style from what I have seen. Array\<any\> is only used in Timeline.d.ts, any[] is used in 36 places across 21 files.

```suggestion
    options?: any[];
```

2021-03-30 11:16 UTC, master117 approved these changes

2021-04-08 06:00 UTC, merged

2021-04-08 06:01 UTC, mertsincan commented
Thanks a lot for your contribution.

Best Regards,