feature(TreeSelect): Add collapseAll and expandAll methods
primefaces/primereact pull request #3160
Opened 2022-08-17 10:16 UTC by arkadiusztw

Solves https://github.com/primefaces/primereact/issues/2964 for TreeSelect

2022-08-17 11:55 UTC, melloware requested changes

2022-08-17 11:55 UTC, melloware commented on components/lib/treeselect/treeselect.d.ts
> +    expandedKeys?: TreeSelectExpandedKeysType;
Please update `\api-generator\components\treeselect.js` with the new `expandedKeys` property as well.

2022-08-17 12:05 UTC, melloware commented
Also looks like you are getting a TypeScript failure: Error: components/lib/treeselect/treeselect.d.ts(60,45): error TS2709: Cannot use namespace 'TreeEventNodeParams' as a type.

Just run `npm run type-check` locally to compile your TS before pushing.

2022-08-17 12:20 UTC, melloware commented
OK I am rerunning the build with your latest changes

2022-08-17 12:45 UTC, melloware approved these changes

2022-08-17 12:47 UTC, melloware requested changes

2022-08-17 12:47 UTC, melloware commented on pages/treeselect/index.js
> +                        <Button
Shoudln';t for this Programmatic Control Demo we only use 1 TreeSelect and use a new TreeSelect. I know Mert likes exact examples and not updating the previous examples?

2022-08-17 13:07 UTC, melloware commented
also if you make a comment on the original ticket it will let me assign you to the ticket.

2022-08-17 14:03 UTC, melloware approved these changes

2022-08-22 09:41 UTC, mertsincan commented
Thanks a lot for your contribution! But, all the formatting in the files seems to have changed. Could you please update your files? After these changes, I or @melloware'll merge this nice feature.

2022-08-22 10:01 UTC, arkadiusztw commented
Do you mean to use prettier on the file components/doc/treeselect/index.js? Or is it about something else?
Please clarify

2022-08-22 10:33 UTC, melloware commented
No he means on your index.JS it looks like you formatted the examples. Just make the smallest necessary changes for review is all Mert is saying.

2022-08-22 11:31 UTC, melloware requested changes

2022-08-22 11:31 UTC, melloware commented on components/doc/treeselect/index.js
> +                    ></TreeSelect>
I think this is what Mert means leave these example flattened not wrapped

2022-08-22 11:45 UTC, melloware commented on components/doc/treeselect/index.js
> +                    ></TreeSelect>
I would just grab the latest index.js and just reapply your new example only.

2022-08-23 12:43 UTC, melloware commented
@arkadiusztw any chance you can fix index.js?

2022-08-23 13:06 UTC, arkadiusztw commented
> @arkadiusztw any chance you can fix index.js?

yes, I just need some time

2022-08-23 22:07 UTC, melloware commented
Since we updated to Prettier I took care of this for you!  Thanks for your PR!

2022-08-23 22:07 UTC, closed without merging