Implemented new support page.
primefaces/primereact pull request #3450
Opened 2022-10-08 13:56 UTC by ulasturann

### Defect Fixes

### Feature Requests
Implementation of the new PRO Support page.

2022-10-08 14:00 UTC, melloware approved these changes

2022-10-08 18:24 UTC, melloware requested changes

2022-10-08 18:24 UTC, melloware commented on pages/support/index.js
> +                            With PRO support, it's easy to support, tune and add features to PrimeNG as if it were an in- house library. PRO is a term based commercial support service. With the exclu
PrimeNG should be PrimeReact

2022-10-08 18:24 UTC, melloware commented on pages/support/index.js
> +                                href="mailto:primeng@primetek.com.tr"
primeng@primetek.com.tr should be primereact?

2022-10-08 18:24 UTC, melloware commented on pages/support/index.js
> +                                href="mailto:primeng@primetek.com.tr"
primeng to primereact

2022-10-08 20:46 UTC, melloware approved these changes

2022-10-10 17:23 UTC, melloware commented
@habubey looks like this PR is conflicting now?

2022-10-10 17:38 UTC, habubey commented
> @habubey looks like this PR is conflicting now?

I have pushed to updated version commit to the master, please consider it while reviewing.
https://github.com/primefaces/primereact/commit/6fbadf89db29f996b00a8e9daab20f7e9e010577

2022-10-11 08:57 UTC, closed without merging