tooltip add access to show/hide through ref
primefaces/primereact pull request #3501
Opened 2022-10-23 16:31 UTC by vasilevich

### Defect Fixes
When submitting a PR, please also <ins>**create an issue**</ins> documenting the error and [manually link to an issue](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#manually-linking-a-pull-request-or-branch-to-an-issue-using-the-issue-sidebar) or mention it in the description using #<issue_id>.

### Feature Requests
Due to company policy, we are unable to accept feature request PRs with significant changes as such cases has to be implemented by our team following our own processes.
Smaller scaled feature implementations such as adding a property to a component will be considered for merging.

2022-10-23 16:31 UTC, vasilevich commented
https://github.com/primefaces/primereact/issues/3500

2022-10-24 00:58 UTC, melloware commented
Need to update the Typescript definition as well.

2022-10-24 00:59 UTC, melloware requested changes
Please add to tooltip.d.at as well

2022-10-24 11:08 UTC, melloware approved these changes

2022-10-24 11:11 UTC, merged