Fix #3934: MultiSelect Add selectAllLabel
primefaces/primereact pull request #3939
Opened 2023-01-10 09:11 UTC by mflagey

Signed-off-by: Mathias Flagey <mathiasflagey1201@gmail.com>

2023-01-10 09:55 UTC, melloware requested changes

2023-01-10 10:19 UTC, mflagey commented on components/lib/multiselect/MultiSelectHeader.js
> +        </div>
Something like this ?

```
const checkboxElement = props.showSelectAll && (
        <div>
            <Checkbox id="select-all-checkbox" checked={props.selectAll} onChange={onSelectAll} role="checkbox" aria-checked={props.selectAll} />
            {props.showSelectAll && !props.filter && <label for="select-all-checkbox" className="p-multiselect-select-all-label">{props.selectAllLabel}</label>}
        </div>
);
 ```

2023-01-10 13:08 UTC, melloware commented on components/lib/multiselect/MultiSelectHeader.js
> +        </div>
Yep except for we need to do this...

```js
import { classNames, ObjectUtils, UniqueComponentId } from '../utils/Utils';

const selectAllId = props.id ? props.id + '_selectall' : UniqueComponentId();
```

if you have multiple MultiSelects on the page it has to be unique so you will also have to pass props.id into the Header.

2023-01-10 13:37 UTC, mflagey commented on components/lib/multiselect/MultiSelectHeader.js
> +        </div>
Ok , I changed it!

2023-01-10 13:48 UTC, melloware approved these changes

2023-01-10 13:48 UTC, melloware commented
Looking pretty good now!

2023-01-10 13:51 UTC, melloware commented
Assigned to PrimeTek to review.

2023-02-14 07:57 UTC, mflagey commented
Hello @melloware @mertsincan,
I have rebase my branch. 
It appears that several files, that I hasn't modified, have format errors and make CI fail.
It's probably a prettier check error from master branch

2023-05-10 17:00 UTC, melloware commented
Can you rebase this PR a lot has changed since your last commit.

2023-07-01 15:36 UTC, merged