fix: fix bad behaviour of Dialog component
primefaces/primereact pull request #4760
Opened 2023-08-10 19:50 UTC by artemlukashenko

Bad behaviour of the Dialog component during the process of dragging: https://github.com/primefaces/primereact/issues/4759

2023-08-10 19:58 UTC, artemlukashenko commented
Hi! @habubey!
I think that we can solve this problem by changing the Dialog component's logic.

2023-08-10 20:17 UTC, melloware requested changes

2023-08-10 20:17 UTC, melloware commented on components/lib/dialog/Dialog.js
> +            const topMargin = parseFloat(getComputedStyle(dialogRef.current)['margin-top'])
I think we need to look at ` const leftPos = offset.left + deltaX;` how the offset is calculated it should account for margin?

2023-08-11 19:57 UTC, melloware requested changes

2023-08-11 19:57 UTC, melloware commented on components/lib/dialog/Dialog.js
> +            const topMargin = parseFloat(getComputedStyle(dialogRef.current)['margin-top'])
```suggestion
            const computedStyle = getComputedStyle(dialogRef.current);
            const leftMargin = parseFloat(computedStyle.marginLeft);
            const topMargin = parseFloat(computedStyle.marginTop);
```

2023-08-11 19:58 UTC, melloware commented
OK I committed a small refactoring to your logic.

2023-08-11 20:08 UTC, merged