Fix primefaces #4875 InputNumber: Doesn't allow minus sign in currency mode, fixed typos and ability to remove - sign
primefaces/primereact pull request #4885
Opened 2023-09-06 16:02 UTC by akshayaqburst

### Defect Fixes
Fix primefaces #4875 Fix primefaces #4875 InputNumber: Doesn't allow minus sign in currency mode.

-Fixed typo issue with previous pr
-Added ability to remove minus sign in currency mode

2023-09-06 16:04 UTC, akshayaqburst commented
@melloware I have fixed the typo issue with the previous PR and also added the ability to remove - sign as requested by @VasiliPodoplielov.
Thanks,

2023-09-06 16:37 UTC, melloware requested changes

2023-09-06 19:20 UTC, akshayaqburst commented on components/lib/inputnumber/InputNumber.js
> +                        } else if (props.mode === 'currency' && ['¥', '$', 'I', 'N', 'R'].includes(deleteChar)) {
Done @melloware

2023-09-06 20:05 UTC, melloware commented
OK there are bigger issues here I need to investigate.

2023-09-07 18:21 UTC, melloware commented
Superseded by this PR: https://github.com/primefaces/primereact/pull/4904

2023-09-07 18:21 UTC, closed without merging