fix(Dialog): scroll block applied incorrectly in some cases
primefaces/primereact pull request #4946
Opened 2023-09-23 12:11 UTC by avasuro

Related tickets: #4940

2023-09-23 12:21 UTC, melloware approved these changes
This looks great.  Let me test it out.

2023-09-23 12:23 UTC, melloware requested changes

2023-09-23 12:23 UTC, melloware commented on components/lib/dialog/Dialog.js
> +                document.primeDialogParams[currentDialogIndexInRegistry] = newParam
We are only supporting modern browsers so I think its OK for you to use toSpliced if its the correct thing to do?

2023-09-23 12:27 UTC, melloware commented
On more thing while you are in there my IDE is showing the method `getPositionClass` as no longer used and I just removed it and verified all the position samples are working correctly. So its something that got moved with unstyled mode but this code was not deleted. Do you mind deleting it as part of this PR please?

2023-09-23 12:37 UTC, avasuro commented
Fixed

2023-09-23 12:37 UTC, melloware commented
@avasuro this is a fantastic PR.  All tested and looks good on my end letting the CI Pipeline run then I will merge!

2023-09-23 12:39 UTC, melloware approved these changes

2023-09-23 12:41 UTC, melloware commented
ahh looks like you need to run `npm run format` to format the code.

2023-09-23 12:57 UTC, melloware commented
The failures are unrelated to this change.  Merging!

2023-09-23 12:57 UTC, merged

2023-09-27 16:54 UTC, ulasturann commented
Hi @avasuro,

Thank you for your contribution through your PR. We've realized that the 'blockScroll' issue isn't related to your PR and have already addressed it. Could you please reopen your PR so that we can incorporate your valuable contribution into v10?

2023-09-27 17:14 UTC, melloware commented
@avasuro @ulasturann I submitted it in a new PR.