Fix #4181 -AvatarGroup: Avatar Hover tooltip
primefaces/primereact pull request #5121
Opened 2023-10-19 20:49 UTC by buraksaglam089

Fix #4181 .

2023-10-19 22:10 UTC, melloware requested changes

2023-10-19 22:10 UTC, melloware commented on components/lib/tooltip/Tooltip.js
> +                if (((isMouseTrack(currentTargetRef.current) || position == 'mouse') && !containerSize.current) || (isMouseTrack(currentTargetRef.current) || position == 'mouse')) {
Since we are calling isMouseTrack method twice here break it out to a const on the line above.

2023-10-26 11:34 UTC, habubey approved these changes

2023-10-26 11:45 UTC, melloware approved these changes

2023-10-26 11:46 UTC, merged