fix(InputMask): Paste at Cursor Selection
primefaces/primereact pull request #5286
Opened 2023-11-10 18:10 UTC by Triggs125

The input mask component currently pastes contents at the first empty value position instead of the cursor selection. Providing an undefined position to the caret function *mostly* fixes this issue because after the paste happens, the cursor is returned to the last empty value position instead of at the end of the newly pasted value.

### Defect Fixes
Fix: https://github.com/primefaces/primereact/issues/5285

2023-11-10 18:14 UTC, melloware commented
thanks @Triggs125 looks good to me but assigned to PrimeTek for testing before merging.

2023-11-10 20:12 UTC, nitrogenous commented
Thank you for addressing this and your contribution. I just took quick view to your code. I will be reviewing and testing it more detailed.

2023-11-13 07:53 UTC, nitrogenous commented
Hey @Triggs125 I reviewed your contribution it looks good but I think we can add one extra parameter to handleInputChange function to prevent code duplication. I have tried this version and it seems working properly. 

```  
const handleInputChange = (e, isOnPaste = false) => {
    if (props.readOnly) {
        return;
    }

    if (!isOnPaste) {
        let pos = checkVal(true);

        caret(pos);
    }

    updateModel(e);

    if (props.onComplete && isCompleted()) {
        props.onComplete({
            originalEvent: e,
            value: getValue()
        });
    }
};
```

```
onPaste={(e) => handleInputChange(e, true)}
```

2023-11-13 07:54 UTC, nitrogenous requested changes
Hey @Triggs125 I reviewed your contribution it looks good but I think we can add one extra parameter to handleInputChange function to prevent code duplication. I have tried this version and it seems working properly. What do you say??

```  
const handleInputChange = (e, isOnPaste = false) => {
    if (props.readOnly) {
        return;
    }

    if (!isOnPaste) {
        let pos = checkVal(true);

        caret(pos);
    }

    updateModel(e);

    if (props.onComplete && isCompleted()) {
        props.onComplete({
            originalEvent: e,
            value: getValue()
        });
    }
};
```

```
onPaste={(e) => handleInputChange(e, true)}
```

2023-11-13 12:45 UTC, melloware commented
I agree with @nitrogenous

2023-11-13 13:43 UTC, melloware approved these changes

2023-11-13 13:55 UTC, gucal approved these changes

2023-11-13 14:00 UTC, melloware commented
Run `npm run format` to fix your formatting issues.

2023-11-13 14:54 UTC, merged