Fix 5415 Action buttons should disabled if any item is not selected
primefaces/primereact pull request #5416
Opened 2023-11-27 14:17 UTC by nitrogenous

#5415

2023-11-27 14:31 UTC, melloware approved these changes

2023-11-27 14:32 UTC, melloware requested changes

2023-11-27 14:32 UTC, melloware commented on components/lib/orderlist/OrderListControls.js
> +    const isMoveDisabled = !props.selection || !props.selection.length ? true : false;
```suggestion
    const isMoveDisabled = ObjectUtils.isEmpty(props.selection);
```

2023-11-29 21:52 UTC, melloware approved these changes

2023-11-30 12:24 UTC, nitrogenous commented on components/lib/orderlist/OrderListControls.js
> +    const isMoveDisabled = !props.selection || !props.selection.length ? true : false;
I missed that thank you for fixing it

2023-11-30 12:24 UTC, merged