Enhancement: DataTable accessibility
primefaces/primereact pull request #5839
Opened 2024-01-25 10:29 UTC by nitrogenous

https://github.com/primefaces/primereact/issues/5799

2024-01-25 23:24 UTC, melloware requested changes

2024-01-25 23:24 UTC, melloware commented on components/lib/datatable/BodyRow.js
>                  case 40:
We should switch those to event.code like 'ArrowDown' etc. the old event.which is deprecated

2024-01-25 23:24 UTC, melloware commented on components/lib/datatable/HeaderCell.js
>              onClick(event);
I don't think we want to use event.which anymore it should all be event.code right?

2024-01-29 13:05 UTC, gucal approved these changes

2024-02-01 13:52 UTC, merged