fix: primefaces #6046, Password: (accessiblility) cannot access toggle button using keyboard
primefaces/primereact pull request #6052
Opened 2024-02-28 13:27 UTC by akshayaqburst

### Defect Fixes
fix: primefaces #6046, Password: (accessiblility) cannot access toggle button using keyboard

2024-02-28 13:38 UTC, melloware requested changes

2024-02-28 13:38 UTC, melloware commented on components/lib/password/Password.js
> +        const onEyeIconKeyPress = (e) => {
```suggestion
        const onToggleMaskKeyDown= (e) => {
```

2024-02-28 13:38 UTC, melloware commented on components/lib/password/Password.js
> +                    onKeyDown: onEyeIconKeyPress
```suggestion
                    onKeyDown: onToggleMaskKeyDown
```

2024-02-28 13:38 UTC, melloware commented on components/lib/password/Password.js
> +                    onKeyDown: onEyeIconKeyPress
```suggestion
                    onKeyDown: onToggleMaskKeyDown
```

2024-02-28 13:42 UTC, melloware commented
Also we need to add to both buttons...

`'aria-label': ariaLabel('toggleMaskLabel') || "Toggle Mask"`

2024-02-28 14:27 UTC, akshayaqburst commented
@melloware resolved comments.

2024-02-28 14:31 UTC, melloware requested changes

2024-02-28 14:31 UTC, melloware commented on components/lib/password/Password.js
> +            return e.key === 'Enter' ? toggleMask() : '';
Do you need the `return` here?
```suggestion
            e.key === 'Enter' && toggleMask();
```

2024-02-28 14:33 UTC, melloware requested changes

2024-02-28 14:33 UTC, melloware commented on components/lib/password/Password.js
> +            return e.key === 'Enter' ? toggleMask() : '';
```suggestion
            if (event.key === 'Enter' || event.key === 'Space') {
                toggleMask();
                event.preventDefault();
            }
```

2024-02-28 14:34 UTC, melloware requested changes

2024-02-28 18:57 UTC, melloware commented
Run `npm run format` and it should be good!

2024-02-28 19:02 UTC, akshayaqburst commented
@melloware Good to review

2024-02-28 19:05 UTC, melloware approved these changes

2024-02-28 19:08 UTC, melloware commented
Thanks this is great!

2024-02-28 19:16 UTC, melloware commented
@akshayaqburst I just read this article https://medium.com/kiipco/password-creation-3-ways-to-make-it-accessible-bc8f2b53b7ee#1751

I think we should chnage two more properties to the icons. Change `role="button"` to `"role="switch"` and add `aria-checked`
 
```
     role: "switch",
     "aria-checked": "false"
```

`aria-checked: "true"` true on the `show` button and false on the `hide` button.

2024-02-28 20:57 UTC, melloware requested changes

2024-02-28 20:57 UTC, melloware commented on components/lib/password/Password.js
> +                    'aria-label': ariaLabel('toggleMaskLabel') || 'Toggle Password Mask'
```suggestion
                    'aria-label': ariaLabel('togglePasswordLabel') || 'Toggle Password Mask'
```

2024-02-28 20:59 UTC, melloware requested changes

2024-02-28 20:59 UTC, melloware commented on components/lib/password/Password.js
>                      role: 'button',
```suggestion
                    role: 'switch',
```

2024-02-28 20:59 UTC, melloware commented on components/lib/password/Password.js
>                      role: 'button',
```suggestion
                    role: 'switch',
```

2024-02-28 20:59 UTC, melloware commented on components/lib/password/Password.js
> +                    'aria-label': ariaLabel('toggleMaskLabel') || 'Toggle Password Mask'
```suggestion
                    'aria-label': ariaLabel('togglePasswordLabel') || 'Toggle Password Mask',
                    'aria-checked': 'true'
```

2024-02-29 07:27 UTC, akshayaqburst commented
@melloware Comments resolved. Thanks,

2024-02-29 12:36 UTC, melloware commented
OK later today I might have one more change for you i am going to update the labels in PrimeLocale and have you change the aria label once last time.  I think I am going to go with 2 labels.

2024-02-29 22:33 UTC, melloware requested changes

2024-02-29 22:33 UTC, melloware commented on components/lib/password/Password.js
> +                    'aria-label': ariaLabel('togglePasswordLabel') || 'Toggle Password Mask',
```suggestion
                    'aria-label': ariaLabel('passwordHide') || 'Hide Password',
```

2024-02-29 22:33 UTC, melloware commented on components/lib/password/Password.js
> +                    'aria-label': ariaLabel('togglePasswordLabel') || 'Toggle Password Mask',
```suggestion
                    'aria-label': ariaLabel('passwordShow') || 'Show Password',
```

2024-03-01 04:16 UTC, akshayaqburst commented
@melloware Good to review. Thanks,

2024-03-01 13:37 UTC, melloware approved these changes

2024-03-05 01:13 UTC, nitrogenous approved these changes

2024-03-18 11:17 UTC, merged

2024-03-18 11:17 UTC, nitrogenous commented
Perfect!