Listbox - focusOnHover prop
primefaces/primereact pull request #6172
Opened 2024-03-18 07:24 UTC by gucal

Fix #6171 Listbox - focusOnHover prop

2024-03-18 10:32 UTC, nitrogenous requested changes
Duplicated types and duplicated default value in listboxbase

2024-03-18 12:20 UTC, melloware requested changes
Looks like some typescript errors or duplicates?

2024-03-18 14:30 UTC, melloware approved these changes

2024-03-19 11:35 UTC, nitrogenous approved these changes

2024-03-20 06:22 UTC, merged