fix: primefaces #6234, TreeSelect: (accessiblility) cannot access and clear the selected input using using keyboard
primefaces/primereact pull request #6235
Opened 2024-03-26 19:02 UTC by akshayaqburst

… 

### Defect Fixes
fix: primefaces #6234, TreeSelect: (accessiblility) cannot access and clear the selected input using using keyboard

2024-03-26 19:14 UTC, akshayaqburst commented
@melloware A PR for review, but its build is failing. **npm run lint:fix** in my local shows a lot of lint changes. Please advice.

2024-03-29 11:32 UTC, nitrogenous commented
FYI This change planned for the next release. Thank you for your contribution

2024-03-29 11:55 UTC, melloware requested changes

2024-03-29 11:55 UTC, melloware commented on components/lib/treeselect/TreeSelect.js
> +                        'aria-label': 'Clear Selection'
```suggestion
                        'aria-label': localeOption('clear')
```

2024-03-30 08:44 UTC, akshayaqburst commented
@melloware done

2024-03-30 10:58 UTC, melloware approved these changes

2024-04-29 13:27 UTC, nitrogenous approved these changes
LGTM

2024-04-29 13:27 UTC, merged