Fix: metergroup typos
primefaces/primereact pull request #6699
Opened 2024-05-28 22:47 UTC by ivanpajon

### Defect Fixes
Fix #6696

2024-05-28 23:12 UTC, melloware commented
Don't we need to update the metergroup.d.ts as well?

2024-05-28 23:13 UTC, melloware requested changes
See comment

2024-05-29 06:49 UTC, ivanpajon reviewed
I don't see any comment...

One of the changes I made was updating the metergroup.d.ts

2024-05-29 11:52 UTC, melloware approved these changes

2024-05-29 11:52 UTC, merged