Correct passthrough (pt) implementation for Stepperpanel.
primefaces/primereact pull request #7069
Opened 2024-08-21 14:16 UTC by Sumeet-2023

Ensured the pt (passthrough) mechanism properly applies Tailwind classes to the stepperpanel.
Example usage:
![image](https://github.com/user-attachments/assets/37ffdfb1-5a2e-4d40-801d-4a30ac038ac5)
or
![image](https://github.com/user-attachments/assets/06e6162b-f0c8-4f6b-a29e-feabfdf6e54e)

### Defect Fixes
Fixes #6910

2024-08-21 15:01 UTC, melloware commented
cc @gcko for review

2024-08-21 15:02 UTC, melloware commented
can you also look at this one: https://github.com/primefaces/primereact/issues/6758

2024-08-21 15:03 UTC, melloware requested changes
Please run `npm run format`

2024-08-21 15:46 UTC, melloware commented
OK stepper unit tests are failing now because the HTML output has changed.

2024-08-21 16:10 UTC, Sumeet-2023 commented
> OK stepper unit tests are failing now because the HTML output has changed.

I had to add/remove attributes in HTML elements like data-pc-section in few components or changing/removing the ptm so that it affects DOM of Stepper/StepperPanel. Do i have to update unit test as well?

2024-08-21 16:45 UTC, melloware commented
yeah you can run `npm test` and then follow the instructions for how to update the snapshots.

2024-08-23 12:58 UTC, melloware approved these changes

2024-08-23 12:58 UTC, merged

2024-08-23 13:04 UTC, Sumeet-2023 commented
> can you also look at this one: #6758

Sure! I was waiting for this PR to be merged. Now i can get started :)

2024-08-23 13:05 UTC, melloware commented
Thanks!

2024-08-23 13:07 UTC, melloware commented
@Sumeet-2023 i think we also need to update stepper.d.ts with the chnages in type styling for passthrough now too

2024-08-23 13:18 UTC, Sumeet-2023 commented
> @Sumeet-2023 i think we also need to update stepper.d.ts with the chnages in type styling for passthrough now too

Maybe i dont think so we need changes in .d.ts file because i made changes in such a way that .d.ts file wont be affected for Stepper component. Or I might have misinterpreted what u wanted to convey.