MultiSelect: Allow to be inline on first render.
primefaces/primereact pull request #7342
Opened 2024-10-15 13:39 UTC by Et7f3

fix #7341 and #6838

### Defect Fixes
When submitting a PR, please also <ins>**create an issue**</ins> documenting the error and [manually link to an issue](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#manually-linking-a-pull-request-or-branch-to-an-issue-using-the-issue-sidebar) or mention it in the description using #<issue_id>.

### Feature Requests
Due to company policy, we are unable to accept feature request PRs with significant changes as such cases has to be implemented by our team following our own processes.
Smaller scaled feature implementations such as adding a property to a component will be considered for merging.

2024-10-15 16:09 UTC, melloware requested changes

2024-10-15 16:09 UTC, melloware commented on components/lib/multiselect/MultiSelect.js
> +            labelContainerRef.current && DomHandler.alignOverlay(overlayRef.current, labelContainerRef.current.parentElement, props.appendTo || (context && context.appendTo) || PrimeReact.appendTo);
```suggestion
            !props.inline && DomHandler.alignOverlay(overlayRef.current, labelContainerRef.current.parentElement, props.appendTo || (context && context.appendTo) || PrimeReact.appendTo);
```

2024-10-16 11:35 UTC, melloware approved these changes

2024-10-16 11:35 UTC, merged

2024-10-16 12:10 UTC, Et7f3 commented
fix #6838

(it was not closed automatically)

So this repo doesn't want to participate in hacktoberfest ?

2024-10-16 12:41 UTC, melloware commented
I would add the tag if I owned the repo but I can't!