fix: #7437, TabView: Unable to select closable icon of tabs through keyboard
primefaces/primereact pull request #7438
Opened 2024-11-20 09:13 UTC by akshayaqburst

fix: #7437, TabView: Unable to select closable icon of tabs through keyboard

2024-11-20 10:03 UTC, melloware requested changes

2024-11-20 10:54 UTC, akshayaqburst commented on components/lib/tabview/TabView.js
> +                onKeyDown: (e) => onCloseIconKeyDown(e, index)
@melloware Done

2024-12-02 06:46 UTC, akshayaqburst commented
@melloware Can we get this merged?

2024-12-02 12:26 UTC, melloware approved these changes

2024-12-02 12:26 UTC, merged